apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: online-inference-replica
  labels:
    name: online-inference-replica
spec:
  replicas: 3
  selector:
    matchLabels:
      name: online-inference-replica
  template:
    metadata:
      labels:
        name: online-inference-replica
    spec:
      containers:
        - image: mivankin/ml_prod_hw2:0.0.2
          name: online-inference-replica
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 200m
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
