apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-inference
  labels:
    name: online-inference
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      name: online-inference
  template:
    metadata:
      labels:
        name: online-inference
    spec:
      containers:
        - name: online-inference
          image: mivankin/ml_prod_hw2:0.0.2
          ports:
            - name: api
              containerPort: 8000
              protocol: TCP
