apiVersion: v1
kind: Pod
metadata:
  name: online-inference
spec:
  containers:
    - image: mivankin/ml_prod_hw2:0.0.2
      name: online-inference
      ports:
        - containerPort: 8000
          protocol: TCP
